theme: jekyll-theme-minimal
title: Sclash

lsi: false
safe: true
source: main
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
